/**
 * @file
 * @ingroup crDemoMaster
 * OutComponent encapsulating a report generated by a Slave Application when a temperature
 * violation has been detected.
 * An OutComponent is defined by defining the functions which override its
 * adaptation points, namely (see <code>CrFwOutCmp.h</code>):
 * - The Enable Check Operation
 * - The Ready Check Operation
 * - The Serialize Operation
 * .
 * These operations are defined as follows for the temperature violation report:
 * - Enable Check Operation: the default Enable Check Operation of
 *   <code>CrFwOutCmpDefEnableCheck.h</code> is used.
 * - Ready Check Operation: the default Ready Check Operation of
 *   <code>CrFwSmCheckAlwaysTrue.h</code> is used.
 * - Serialize Operation: this operation calls the default Serialize Operation of
 *   <code>CrFwOutCmpDefSerialize.h</code> and then it writes the temperature
 *   which violated the limit in the first byte of the parameter part of the report packet;
 *   and it sets the command destination to be the Master Application.
 * .
 *
 * @author Vaclav Cechticky <vaclav.cechticky@pnp-software.com>
 * @author Alessandro Pasetti <pasetti@pnp-software.com>
 * @copyright P&P Software GmbH, 2013, All Rights Reserved
 * @version GPLv3_0.7.1
 *
 * This file is part of CORDET Framework.
 *
 * CORDET Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CORDET Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with CORDET Framework.  If not, see <http://www.gnu.org/licenses/>.
 *
 * For information on alternative licensing, please contact P&P Software GmbH.
 */

#ifndef CRMA_OUTCMP_TEMP_VIOLATION_H_
#define CRMA_OUTCMP_TEMP_VIOLATION_H_

/* Include framework components */
#include "CrFwConstants.h"
/* Include FW Profile components */
#include "FwSmCore.h"

/**
 * Implementation of the Serialize Operation for the report for a temperature violation.
 * This operation calls the default Serialize Operation of
 * <code>CrFwOutCmpDefSerialize.h</code> and then writes the temperature
 * which violated the limit in the first byte of the parameter part of the report packet;
 * and it sets the command destination to be the Master Application.
 * The value of the limit violating temperature is set through function
 * <code>CrDaOutCmpTempViolationSetTemp</code>.
 * @param smDesc the descriptor of the OutComponent state machine
 * @return the value of the Enable Flag
 */
void CrDaOutCmpTempViolationSerialize(FwSmDesc_t smDesc);

/**
 * Set the value of the limit violating temperature (an integer in the range 0 to 255).
 * @param temp the limit violating temperature
 */
void CrDaOutCmpTempViolationSetTemp(char temp);

#endif /* CRMA_OUTCMP_TEMP_VIOLATION_H_ */
