/**
 * @file
 * @ingroup crConfigDemoMaster
 * Implementation of the error reporting interface of <code>CrFwRepErr.h</code>
 * for the Master Application of the CORDET Demo.
 * This implementation writes the error reports to standard output.
 *
 * @author Vaclav Cechticky <vaclav.cechticky@pnp-software.com>
 * @author Alessandro Pasetti <pasetti@pnp-software.com>
 * @copyright P&P Software GmbH, 2013, All Rights Reserved
 * @version GPLv3_0.7.1
 *
 * This file is part of CORDET Framework.
 *
 * CORDET Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CORDET Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with CORDET Framework.  If not, see <http://www.gnu.org/licenses/>.
 *
 * For information on alternative licensing, please contact P&P Software GmbH.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* Include Framework Files */
#include "CrFwConstants.h"
#include "CrFwRepErr.h"

/*-----------------------------------------------------------------------------------------*/
void CrFwRepErr(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId, CrFwInstanceId_t instanceId) {
	printf("CrFwErrRep: error %d generated by component %d of type %d\n", errCode,instanceId,typeId);
}

/*-----------------------------------------------------------------------------------------*/
void CrFwRepErrDestSrc(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId, CrFwInstanceId_t instanceId,
                       CrFwDestSrc_t destSrc) {
	printf("CrFwRepErrDestSrc: error %d generated by component %d of type %d for dest/src %d\n",
	       errCode,instanceId,typeId,destSrc);
}

/*-----------------------------------------------------------------------------------------*/
void CrFwRepErrInstanceIdAndDest(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId,
                                 CrFwInstanceId_t instanceId, CrFwInstanceId_t secondaryInstanceId, CrFwDestSrc_t dest) {
	printf("CrFwRepErrInstanceIdAndDest: error %d generated by component %d of type %d\n",errCode,instanceId,typeId);
	printf("                             secondary sequence identifier: %d, destination: %d\n",secondaryInstanceId,dest);
}

/*-----------------------------------------------------------------------------------------*/
void CrFwRepErrSeqCnt(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId, CrFwInstanceId_t instanceId,
                      CrFwSeqCnt_t expSeqCnt, CrFwSeqCnt_t actSeqCnt) {
	printf("CrFwRepErrSeqCnt: error %d generated by component %d of type %d\n",errCode,instanceId,typeId);
	printf("                  expected sequence counter: %d, actual sequence counter: %d\n",expSeqCnt,actSeqCnt);
}

/*-----------------------------------------------------------------------------------------*/
void CrFwRepErrGroup(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId, CrFwInstanceId_t instanceId,
                     CrFwGroup_t group) {
	printf("CrFwRepErrGroup: error %d generated by component %d of type %d\n",errCode,instanceId,typeId);
	printf("                  invalid group: %d\n",group);

}

/*-----------------------------------------------------------------------------------------*/
void CrFwRepErrInstanceIdAndOutcome(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId,
                                    CrFwInstanceId_t instanceId, CrFwInstanceId_t secondaryInstanceId, CrFwOutcome_t outcome) {
	printf("CrFwRepErrInstanceIdAndOutcome: error %d generated by component %d of type %d\n",errCode,instanceId,typeId);
	printf("                                secondary sequence identifier: %d, outcome: %d\n",secondaryInstanceId,outcome);
}

